
--CREATE TABLE worker (
--    ID BIGINT NOT NULL PRIMARY KEY,
--    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2),
--	BIRTHDAY DATE CHECK( BIRTHDAY >= '1901-01-01'),
--	LEVEL ENUM ('Trainee', 'Junior', 'Middle', 'Senior'),
--	SALARY INT  CHECK (SALARY >= 100 AND SALARY <= 100000)
--);

CREATE TABLE client (
	ID BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(1000) NOT NULL CHECK (LENGTH(NAME) >= 2)
);

--CREATE TABLE project (
--	ID BIGINT NOT NULL PRIMARY KEY,
--    CLIENT_ID BIGINT NOT NULL,
--	START_DATE DATE,
--	FINISH_DATE DATE,
--	FOREIGN KEY(CLIENT_ID)  REFERENCES client(ID)
--);
--
--CREATE TABLE project_worker (
--	PROJECT_ID BIGINT NOT NULL,
--    WORKER_ID BIGINT NOT NULL,
--	PRIMARY KEY (PROJECT_ID, WORKER_ID),
--    FOREIGN KEY(PROJECT_ID) REFERENCES project(ID),
--    FOREIGN KEY (WORKER_ID) REFERENCES worker(ID)
--);


